name: Build PKG

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: docker/setup-qemu-action@v3.0.0
      with:
        platforms: arm64
      
    - uses: actions/checkout@v3
    - name: Run the build
      run: docker run --platform=linux/arm64 -v /usr/bin/qemu-aarch64:/usr/bin/qemu-aarch64 -v `pwd`:/RefresherPS3 zeldin/ps3dev-docker /RefresherPS3/ci-docker-build.sh
